[tools]

# Core dependencies
go = "1.22.3"
rust = "1.83.0"
just = "1.37.0"

# Go dependencies
"ubi:goreleaser/goreleaser" = "2.5.1"
"ubi:golangci/golangci-lint" = "v1.63.4"

# Foundry dependencies
# Foundry is a special case because it supplies multiple binaries at the same
# GitHub release, so we need to use the aliasing trick to get mise to not error
forge = "nightly-017c59d6806ce11f1dc131f8607178efad79d84a"
cast = "nightly-017c59d6806ce11f1dc131f8607178efad79d84a"
anvil = "nightly-017c59d6806ce11f1dc131f8607178efad79d84a"

# Foundry provides multiple binaries so we alias them here
[alias]
forge = "ubi:foundry-rs/foundry[exe=forge]"
cast = "ubi:foundry-rs/foundry[exe=cast]"
anvil = "ubi:foundry-rs/foundry[exe=anvil]"