version: 2.1

executors:
  default:
    machine:
      image: ubuntu-2204:2024.08.1

orbs:
  go: circleci/go@2.2.3
  utils: ethereum-optimism/circleci-utils@0.0.13

commands:
  # By default, CircleCI does not checkout any submodules
  # 
  # In our case, we need to checkout the submodules recursively
  # (since e.g. optimism has its own submodules)
  checkout-with-submodules:
    steps:
      - checkout
      - run: 
          name: Sync submodules
          command: git submodule sync
      - run: 
          name: Initialize submodules
          command: git submodule update --init --recursive
  
  install-dependencies:
    steps:
      - run:
          name: Install mise
          command: curl https://mise.run | MISE_INSTALL_PATH=/home/circleci/bin/mise sh
      - run:
          name: Activate mise
          command: echo 'eval "$(mise activate bash)"' >> $BASH_ENV
      - run:
          name: Install mise dependencies
          command: mise install

  install-go-modules:
    steps:
      - go/load-mod-cache # Load cached Go modules.
      - go/mod-download # Run 'go mod download'.
      - go/save-mod-cache # Save Go modules to cache.

jobs:
  check-versions-monorepo:
    executor: default
    steps:
      - checkout-with-submodules
      - install-dependencies
      - run:
          name: Check versions
          command: just check-monorepo-versions

  contracts-tests:
    executor: default
    environment:
      FOUNDRY_PROFILE: ci
    steps:
      - checkout-with-submodules
      - install-dependencies
      - run:
          name: Run Forge build
          command: just build-contracts
      - run:
          name: Run Forge tests
          command: just test-contracts

  go-lint:
    executor: default
    steps:
      - checkout-with-submodules
      - install-dependencies
      - run:
          name: Run linter
          command: just lint-go

  go-tests:
    executor: default
    steps:
      - checkout-with-submodules
      - install-dependencies
      - install-go-modules
      - run:
          # We need to "rename" some of the variables coming from the CircleCI context
          # to match what supersim expects
          name: Setup environment variables
          command: |
            echo "export SUPERSIM_RPC_URL_MAINNET=$RPC_URL_ETHEREUM_MAINNET" >> $BASH_ENV
            echo "export SUPERSIM_RPC_URL_OP=$RPC_URL_OP_MAINNET" >> $BASH_ENV
            echo "export SUPERSIM_RPC_URL_BASE=$RPC_URL_BASE_MAINNET" >> $BASH_ENV
      - run:
          name: Run tests
          command: just test-go
          no_output_timeout: 20m
    
  go-release:
    executor: default
    steps:
      - checkout-with-submodules
      - install-dependencies
      - install-go-modules
      - utils/get-github-access-token:
          # GoReleaser uses the GITHUB_TOKEN environment variable to authenticate with GitHub
          # 
          # It's important that the token has write permissions both to this repository and to the homebrew-tap repository
          output-token-name: GITHUB_TOKEN
      - run:
          name: Run GoReleaser
          command: goreleaser release --clean

  book-build:
    executor: default
    environment:
      MISE_ENV: book
    steps:
      - checkout
      - install-dependencies
      - run:
          name: Build book
          command: just build-book
      - persist_to_workspace:
          root: ./docs
          paths:
            - book

  book-publish:
    executor: default
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/docs
      - utils/get-github-access-token
      - utils/github-pages-deploy:
          src-pages-dir: /tmp/docs/book

workflows:
  main:
    jobs:
      - check-versions-monorepo
      - contracts-tests
      - go-lint
      - go-tests:
          context:
            - oplabs-rpc-urls
      
      # To tighten the security, we split the workflow that publishes GitHub Pages
      # into two jobs and only expose the security context to the job that does the publishing
      # 
      # The build job will run on every PR to avoid unpleasant surprises if the book build fails on main
      - book-build
      # The publish job will only run on the main branch
      - book-publish:
          filters:
            branches:
              only:
                - main
          requires:
            - book-build
          context:
            - circleci-repo-supersim

  release:
    jobs:
      - go-release:
          context:
            - circleci-repo-supersim
          filters: 
            tags:
              only: 
                - /^v?\d+\.\d+\.\d+.*?/
            # Without explicitly ignoring all branches, CircleCI will run the job on all branches
            # even if no tags have been pushed
            branches:
              ignore: /.*/
